/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import dao.NguoiDungDAO;
import entity.NguoiDung;
import helper.Auth;
import helper.MsgBox;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import main.ManHinhChinh;

/**
 *
 * @author admin
 */
public class PanelDN extends javax.swing.JPanel {

    public PanelDN() {
        initComponents();
        login.setVisible(true);
        Pass.setVisible(false);
        //lblBatLoi.setVisible(false);
    }
    NguoiDungDAO dao = new NguoiDungDAO();
    static String username, hoTen, ChucVu;
    static int cuaso = 0;
    private ActionListener event;

    public void addEvent(ActionListener event) {
        this.event = event;
    }

    public boolean checkDangNhap() {
        String tenDangNhap = txtUserName.getText().trim();
        String matKhau = pswPass.getText();
        NguoiDung nd = dao.selectById(tenDangNhap);
        if (nd != null) {    //nếu manv đúng

            String matKhau2 = nd.getMatKhau();

            if (!matKhau.equals(matKhau2)) {  //nếu mật khẩu đúng
                cuaso = 2;
            } else {
                Auth.user = nd;
                // System.out.println(Auth.getManager());
                cuaso = 1;
            }
        } else {
            cuaso = 3;

        }
        if (tenDangNhap.isEmpty() && matKhau.isEmpty()) {
            lblCheckUser.setText("Vui lòng nhập tên đăng nhập *");
            lblCheckPass.setText("Vui lòng nhập mật khẩu *");
            return false;
        }
        if (tenDangNhap.isEmpty()) {
            lblCheckUser.setText("Vui lòng nhập tên đăng nhập *");
            return false;
        } else if (!tenDangNhap.isEmpty()) {
            if (cuaso == 3) {
                lblCheckUser.setText("Tài khoản không tồn tại! *");
                lblCheckPass.setText("");
                return false;
            }
            lblCheckUser.setText("");

        }
        if (matKhau.isEmpty()) {
            lblCheckPass.setText("Vui lòng nhập mật khẩu *");
            return false;
        } else if (!matKhau.isEmpty()) {
            if (cuaso == 2) {
                lblCheckPass.setText("Mật khẩu sai ! *");
                return false;

            }
            lblCheckPass.setText("");

        }
        return true;

    }

    public void resignShow(boolean show) {
        if (show) {
            Pass.setVisible(false);
            login.setVisible(true);
        } else {
            login.setVisible(false);
            Pass.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new TextAndPassFiled.MyTextField();
        pswPass = new TextAndPassFiled.MyPasswordField();
        btnLogin = new newpackage.Button();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCheckUser = new javax.swing.JLabel();
        lblCheckPass = new javax.swing.JLabel();
        Pass = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName1 = new TextAndPassFiled.MyTextField();
        btnQuenPass = new newpackage.Button();

        setBackground(new java.awt.Color(255, 51, 0));
        setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");

        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txtUserName.setColor(new java.awt.Color(255, 255, 255));
        txtUserName.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtUserName.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        txtUserName.setHint("Tên đăng nhập *");
        txtUserName.setSelectionColor(new java.awt.Color(0, 51, 204));

        pswPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        pswPass.setColor(new java.awt.Color(255, 255, 255));
        pswPass.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        pswPass.setHint("Mật khẩu *");
        pswPass.setSelectionColor(new java.awt.Color(0, 51, 204));

        btnLogin.setBackground(new java.awt.Color(51, 102, 255));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setMaximumSize(new java.awt.Dimension(100, 3));
        btnLogin.setMinimumSize(new java.awt.Dimension(100, 3));
        btnLogin.setPreferredSize(new java.awt.Dimension(100, 3));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_password_32px.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_32px_1.png"))); // NOI18N

        lblCheckUser.setBackground(new java.awt.Color(255, 0, 0));
        lblCheckUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCheckUser.setForeground(new java.awt.Color(252, 83, 117));

        lblCheckPass.setBackground(new java.awt.Color(255, 0, 0));
        lblCheckPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCheckPass.setForeground(new java.awt.Color(252, 83, 117));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCheckUser, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(pswPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCheckPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCheckUser, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(pswPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCheckPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        add(login, "card3");

        Pass.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUÊN MẬT KHẨU ?");

        txtUserName1.setColor(new java.awt.Color(232, 255, 245));
        txtUserName1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtUserName1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtUserName1.setHint("Tên đăng nhập");
        txtUserName1.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_32px_1.png"))); // NOI18N
        txtUserName1.setSelectionColor(new java.awt.Color(83, 255, 150));

        btnQuenPass.setBackground(new java.awt.Color(0, 153, 153));
        btnQuenPass.setForeground(new java.awt.Color(255, 255, 255));
        btnQuenPass.setText("Lấy lại mật khẩu");
        btnQuenPass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout PassLayout = new javax.swing.GroupLayout(Pass);
        Pass.setLayout(PassLayout);
        PassLayout.setHorizontalGroup(
            PassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PassLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(PassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuenPass, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        PassLayout.setVerticalGroup(
            PassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnQuenPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        add(Pass, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (checkDangNhap()) {

            event.actionPerformed(evt);
        }


    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pass;
    private newpackage.Button btnLogin;
    private newpackage.Button btnQuenPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCheckPass;
    private javax.swing.JLabel lblCheckUser;
    private javax.swing.JPanel login;
    private TextAndPassFiled.MyPasswordField pswPass;
    private TextAndPassFiled.MyTextField txtUserName;
    private TextAndPassFiled.MyTextField txtUserName1;
    // End of variables declaration//GEN-END:variables
}
